# Generated by Django 6.0.1 on 2026-01-18 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_category_options_alter_transaction_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='type',
            field=models.CharField(choices=[('cash', 'Наличные'), ('uzcard', 'bank'), ('visa', 'Visa')], max_length=20, verbose_name='Тип'),
        ),
    ]
