# Generated by Django 6.0.1 on 2026-01-15 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_wallet_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='category/')),
                ('type', models.CharField(choices=[('income', 'INCOME'), ('outcome', 'OUTCOME')], max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='expenses',
            name='category',
        ),
        migrations.RemoveField(
            model_name='income',
            name='category',
        ),
        migrations.RemoveField(
            model_name='expenses',
            name='user',
        ),
        migrations.RemoveField(
            model_name='expenses',
            name='wallet',
        ),
        migrations.RemoveField(
            model_name='income',
            name='user',
        ),
        migrations.RemoveField(
            model_name='income',
            name='wallet',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='name',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='user',
        ),
        migrations.AddField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wallet',
            name='card_numbers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='expire_date',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='type',
            field=models.CharField(choices=[('cash', 'CASH'), ('uzcard', 'UzCard'), ('humo', 'HUMO'), ('visa', 'VISA')], default='CASH', max_length=50),
        ),
        migrations.CreateModel(
            name='IncomeOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('income', 'INCOME'), ('outcome', 'OUTCOME')], max_length=15)),
                ('come_type', models.CharField(choices=[('cash', 'CASH'), ('uzcard', 'UzCard'), ('humo', 'HUMO'), ('visa', 'VISA')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('desc', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='main.category')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to='main.wallet')),
            ],
        ),
        migrations.DeleteModel(
            name='CategoryExpenses',
        ),
        migrations.DeleteModel(
            name='CategoryIncome',
        ),
        migrations.DeleteModel(
            name='Expenses',
        ),
        migrations.DeleteModel(
            name='Income',
        ),
    ]
